version: "3.6"
services:
  backbone1:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone1
        target: /etc/bird
    networks:
      - backbone1-backbone2
      - backbone6-backbone1
      - deadendnormal1-backbone1
  backbone2:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone2
        target: /etc/bird
    networks:
      - backbone1-backbone2
      - backbone2-backbone3
      - asbrnormal1-backbone2
  backbone3:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone3
        target: /etc/bird
    networks:
      - backbone2-backbone3
      - backbone3-backbone4
  backbone4:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone4
        target: /etc/bird
    networks:
      - backbone3-backbone4
      - backbone4-backbone5
  backbone5:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone5
        target: /etc/bird
    networks:
      - backbone4-backbone5
      - backbone5-backbone6
  backbone6:
    cap_add:
      - NET_ADMIN
    image: pierky/bird:1.6.6
    volumes:
      - type: bind
        source: ./backbone6
        target: /etc/bird
    networks:
      - backbone5-backbone6
      - backbone6-backbone1

  # Deadend normal area section
  deadendnormal1:
    cap_add:
      - NET_ADMIN
    image: pierky/bird:1.6.6
    volumes:
      - type: bind
        source: ./deadendnormal1
        target: /etc/bird
    networks:
      - deadendnormal1-backbone1
      - deadendnormal1-deadendnormal2
  deadendnormal2:
    cap_add:
      - NET_ADMIN
    image: pierky/bird:1.6.6
    volumes:
      - type: bind
        source: ./deadendnormal2
        target: /etc/bird
    networks:
      - deadendnormal1-deadendnormal2

  # normal area with an ASBR section
  asbrnormal1:
    cap_add:
      - NET_ADMIN
    image: pierky/bird:1.6.6
    volumes:
      - type: bind
        source: ./asbrnormal1
        target: /etc/bird
    networks:
      - asbrnormal1-backbone2
      - asbrnormal1-asbrnormal2
  asbrnormal2:
    cap_add:
      - NET_ADMIN
    image: pierky/bird:1.6.6
    volumes:
      - type: bind
        source: ./asbrnormal2
        target: /etc/bird
    networks:
      - asbrnormal1-asbrnormal2

networks:
  backbone1-backbone2:
    ipam:
      config:
        - subnet: 172.20.1.0/24
  backbone2-backbone3:
    ipam:
      config:
        - subnet: 172.20.2.0/24
  backbone3-backbone4:
    ipam:
      config:
        - subnet: 172.20.3.0/24
  backbone4-backbone5:
    ipam:
      config:
        - subnet: 172.20.4.0/24
  backbone5-backbone6:
    ipam:
      config:
        - subnet: 172.20.5.0/24
  backbone6-backbone1:
    ipam:
      config:
        - subnet: 172.20.6.0/24

  # Links for backbone to deadend normal area
  deadendnormal1-backbone1:
    ipam:
      config:
        - subnet: 172.20.7.0/24
  deadendnormal1-deadendnormal2:
    ipam:
      config:
        - subnet: 172.20.8.0/24

  # Links for backbone to ASBR connected normal area
  asbrnormal1-backbone2:
    ipam:
      config:
        - subnet: 172.20.9.0/24
  asbrnormal1-asbrnormal2:
    ipam:
      config:
        - subnet: 172.20.10.0/24
