version: "3.6"
services:
  backbone1:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone1
        target: /etc/bird
    networks:
      - backbone1-2
      - backbone6-1
  backbone2:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone2
        target: /etc/bird
    networks:
      - backbone2-3
      - backbone1-2
  backbone3:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone3
        target: /etc/bird
    networks:
      - backbone3-4
      - backbone2-3
  backbone4:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone4
        target: /etc/bird
    networks:
      - backbone4-5
      - backbone3-4
  backbone5:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone5
        target: /etc/bird
    networks:
      - backbone5-6
      - backbone4-5
  backbone6:
    cap_add:
      - NET_ADMIN
    image: pierky/bird:1.6.6
    volumes:
      - type: bind
        source: ./backbone6
        target: /etc/bird
    networks:
      - backbone6-1
      - backbone5-6

networks:
  backbone1-2:
  backbone2-3:
  backbone3-4:
  backbone4-5:
  backbone5-6:
  backbone6-1:
