version: "3.6"
services:
  backbone1:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone1
        target: /etc/bird
    networks:
      - backbone1-backbone2
      - backbone6-backbone1
  backbone2:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone2
        target: /etc/bird
    networks:
      - backbone2-backbone3
      - backbone1-backbone2
  backbone3:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone3
        target: /etc/bird
    networks:
      - backbone3-backbone4
      - backbone2-backbone3
  backbone4:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone4
        target: /etc/bird
    networks:
      - backbone4-backbone5
      - backbone3-backbone4
  backbone5:
    image: pierky/bird:1.6.6
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./backbone5
        target: /etc/bird
    networks:
      - backbone5-backbone6
      - backbone4-backbone5
  backbone6:
    cap_add:
      - NET_ADMIN
    image: pierky/bird:1.6.6
    volumes:
      - type: bind
        source: ./backbone6
        target: /etc/bird
    networks:
      - backbone6-backbone1
      - backbone5-backbone6

networks:
  backbone1-backbone2:
  backbone2-backbone3:
  backbone3-backbone4:
  backbone4-backbone5:
  backbone5-backbone6:
  backbone6-backbone1:
